
export const NOTION_QUERY = 'NOTION_QUERY';
export const NOTION_DATABASE = 'NOTION_DATABASE';

export const SEARCH_TYPE = 'SEARCH_TYPE';
export const SEARCH_TYPE_COMPLEX = 'SEARCH_TYPE_COMPLEX';
export const SEARCH_TYPE_SIMPLE = 'SEARCH_TYPE_SIMPLE';
export const SEARCH_INFO = 'SEARCH_INFO';
export const SEARCH_FIELD = 'SEARCH_FIELD';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_INCLUDE = 'SEARCH_INCLUDE';
export const SEARCH_DEPTH = 'SEARCH_DEPTH';
export const SEARCH_PROPERTY = 'SEARCH_PROPERTY';

export const CRUD_RESULT_STATUS = 'CRUD_RESULT_STATUS';
export const CRUD_ERROR = 'CRUD_ERROR';
export const CRUD_RESULT_STATUS_SUCCESS = 'CRUD_RESULT_STATUS_SUCCESS';
export const CRUD_RESULT_STATUS_FAILURE = 'CRUD_RESULT_STATUS_FAILURE';
export const CRUD_RESULT_STATUS_PENDING = 'CRUD_RESULT_STATUS_PENDING';


//KEYS FOR OUR DATA OBJECTS
export const IDGMD_FILTERED_DATA = 'IDGMD_FILTERED_DATA';
export const IDGMD_LIVE_DATA = 'IDGMD_LIVE_DATA';
export const IDGMD_DATA = 'IDGMD_DATA';
export const IDGMD_VALID_DATA = 'IDGMD_VALID_DATA';
export const IDGMD_PRIMARY_DBID = 'IDGMD_PRIMARY_DBID';
export const IDGMD_RELATION_DBIDS = 'IDGMD_RELATION_DBIDS';
