
export const NOTION_QUERY = 'NOTION_QUERY';
export const NOTION_DATABASE = 'NOTION_DATABASE';

export const SEARCH_TYPE = 'SEARCH_TYPE';
export const SEARCH_TYPE_COMPLEX = 'SEARCH_TYPE_COMPLEX';
export const SEARCH_TYPE_SIMPLE = 'SEARCH_TYPE_SIMPLE';
export const SEARCH_INFO = 'SEARCH_INFO';
export const SEARCH_FIELD = 'SEARCH_FIELD';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_INCLUDE = 'SEARCH_INCLUDE';
export const SEARCH_DEPTH = 'SEARCH_DEPTH';
export const SEARCH_PROPERTY = 'SEARCH_PROPERTY';

const URL_SEARCH_PARAM_PAGE_CURSOR_TYPE_REQUEST = 'c';
const URL_SEARCH_PARAM_PAGE_CURSOR_ID_REQUEST = 'i';
const URL_PAGE_CURSOR_TYPE_SPECIFIC = 's';

const NOTION_HAS_MORE = 'has_more';
const NOTION_NEXT_CURSOR = 'next_cursor';


export const SNAPSHOT_TIMESTAMP = 'SNAPSHOT_TIMESTAMP';


export const CRUD_RESULT_STATUS = 'CRUD_RESULT_STATUS';
export const CRUD_ERROR = 'CRUD_ERROR';
export const CRUD_RESULT_STATUS_SUCCESS = 'CRUD_RESULT_STATUS_SUCCESS';
export const CRUD_RESULT_STATUS_FAILURE = 'CRUD_RESULT_STATUS_FAILURE';
export const CRUD_RESULT_STATUS_PENDING = 'CRUD_RESULT_STATUS_PENDING';


//KEYS FOR OUR DATA OBJECTS
export const DGMD_FILTERED_DATA = 'DGMD_FILTERED_DATA';
export const DGMD_LIVE_DATA = 'DGMD_LIVE_DATA';
export const DGMD_DATA = 'DGMD_DATA';
